# IMPORTS
from math import pi, tan, asin, cos, sin, acos, ceil

data = \
{
	'Input Data': {
		'C2': [None, '-', 'Material'],
		'C3': [None, 'r [t/m3]', 'Bulk density'],
		'C4': [None, 'f [°]', 'Repose angle'],
		'C5': [None, 'materials[data["Input Data"]["C2"][0]'],
		'C6': [None, 'Q [t/h]', 'Nominal Required Capacity[0]'],
		'C7': [None, 'data["Input Data"]["C6"][0] / data["Input Data"]["C3"][0] / 3600'],
		'C8': [None, 'D [m]', 'Diameter (on cutting edge)'],
		'C9': [None, 'wBW [rpm]', 'Bucket wheel rotational speed'],
		'C10': [None, 'z', 'Number of buckets'],
		'C11': [None, 'Vb [m3] ', 'Bucket volume'],
		'C12': [None, 'tE [m]', 'Bucket height'],
		'C13': [None, 'bE [m]', 'Bucket width'],
		'C14': [None, '1.24 * pi / 4 * data["Input Data"]["C12"][0] ** 2 * data["Input Data"]["C13"][0]'],
		'C15': [None, 'θ [°]', 'Angle in which bucket discharge starts, measured from vert'],
		'C16': [None, 'm ', 'Efficiency of Drive (Coupling+Motor+Gearbox)'],
		'C17': [None, 'f', 'Bucket Efficiency (filling factor)'],
		'C18': [None, 'data["Input Data"]["C17"][0] * data["Input Data"]["C3"][0] * data["Input Data"]["C11"][0] * data["Input Data"]["C65"][0] * 3600'],
		'C19': [None, 'data["Input Data"]["C18"][0] / data["Input Data"]["C3"][0] / 3600'],
		'C20': [None, 'Lb [m]', 'Boom Lenght'],
		'C21': [None, 'HL [m]', 'Height of boom hinge from bottom of yard'],
		'C22': [None, 'l [m]', 'Distance of boom hinge from slewing axle'],
		'C23': [None, 'h  [m]', 'Height of BW axle from boom hinge (with boom horizontal)'],
		'C24': [None, 'd [m]', 'Distance between pile CL and slewing axle'],
		'C25': [None, 'vSmax  [m/min]', 'Maximum selected boom slewing speed'],
		'C26': [None, 'Hp [m]', 'Stockpile height'],
		'C27': [None, 'Bp [m]', 'Bottom stockpile width'],
		'C28': [None, 'Lp [m]', 'Stockpile lenght (of the full stockpile section)'],
		'C29': [None, 'data["Input Data"]["C27"][0] - 2 * data["Input Data"]["C26"][0] / tan(data["Input Data"]["C47"][0])'],
		'C30': [None, 'asin((data["Input Data"]["C24"][0] - data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0])'],
		'C31': [None, 'data["Input Data"]["C30"][0] * 180 / pi'],
		'C32': [None, 'data["Input Data"]["C31"][0][0]'],
		'C33': [None, 'pi / 2 if (data["Input Data"]["C24"][0] + data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0] < 1 else asin((data["Input Data"]["C24"][0] + data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0])'],
		'C34': [None, 'data["Input Data"]["C33"][0] * 180 / pi'],
		'C35': [None, 'ymax [°]', 'Selected Maximum angle of Reclaiming (in plant view)'],
		'C36': [None, 'a1 [°/s2]', 'Slewing acceleration[0]'],
		'C37': [None, 'data["Input Data"]["C36"][0] * pi / 180'],
		'C38': [None, 'a2 [°/s2]', 'Slewing deceleration[0]'],
		'C39': [None, 'data["Input Data"]["C38"][0] * pi / 180'],
		'C40': [None, 'data["Input Data"]["Stockpile height"] / data["Input Data"]["C8"][0] * 2'],
		'C41': [None, '-', 'Number of selected benches'],
		'C42': [None, 'data["Input Data"]["C12"][0] / cos(data["Input Data"]["C75"][0])'],
		'C43': [None, 'p [m]', 'Selected Step of Reclaiming[0]'],
		'C44': [None, 'data["Input Data"]["C15"][0]'],
		'C46': [None, 'materials[data["Input Data"]["C2"][0]][1]'],
		'C47': [None, 'data["Input Data"]["C4"][0] * pi / 180'],
		'C48': [None, 'materials[data["Input Data"]["C2"][0]][0]'],
		'C51': [None, 'data["Input Data"]["C52"][0] * 180 / pi'],
		'C52': [None, 'asin((0.98 * data["Input Data"]["C23"][0] + data["Input Data"]["C21"][0] - data["Input Data"]["C8"][0] / 2) / data["Input Data"]["C20"][0] '],
		'C53': [None, 'data["Input Data"]["Maximum luffing angle"][0] * 180 / pi'],
		'C54': [None, 'asin((data["Input Data"]["C26"][0] - data["Input Data"]["C21"][0] - 0.985 *  data["Input Data"]["C23"][0] + data["Input Data"]["C8"][0] / 2) / data["Input Data"]["C20"][0]) '],
		'C55': [None, 'data["Input Data"]["C22"][0] + data["Input Data"]["C20"][0] * cos(data["Input Data"]["C52"][0]) + data["Input Data"]["C23"][0] * sin(data["Input Data"]["C52"][0]) + data["Input Data"]["C8"][0] / 2 * sin(data["Input Data"]["C47"][0])'],
		'C57': [None, 'data["Input Data"]["C6"][0] / data["Input Data"]["C3"][0] / data["Input Data"]["C17"][0]'],
		'C58': [None, 'data["Input Data"]["C9"][0] * 2 * pi / 60'],
		'C59': [None, 'data["Input Data"]["Rotational speed"][0] * data["Input Data"]["C8"][0] / 2'],
		'C60': [None, 'data["Input Data"]["C59"][0] * 60'],
		'C61': [None, '2 * pi  / data["Input Data"]["C10"][0]'],
		'C62': [None, '360 / data["Input Data"]["C10"][0]'],
		'C63': [None, '60 / data["Input Data"]["C9"][0] / data["Input Data"]["C10"][0]'],
		'C64': [None, 'data["Input Data"]["C9"][0] * data["Input Data"]["C10"][0]'],
		'C65': [None, 'data["Input Data"]["C64"][0] / 60'],
		'C66': [None, '3.14 * data["Input Data"]["C8"][0] / data["Input Data"]["C10"][0]'],
		'C67': [None, 'data["Input Data"]["C25"][0] / 60'],
		'C68': [None, 'data["Input Data"]["C70"][0] * data["Input Data"]["C69"][0]'],
		'C69': [None, 'data["Input Data"]["C20"][0] + data["Input Data"]["C8"][0] / 2 * sin(data["Input Data"]["C5"][0]) + data["Input Data"]["C22"][0]'],
		'C70': [None, 'data["Input Data"]["C11"][0] * data["Input Data"]["C17"][0] * data["Input Data"]["C65"][0] / data["Input Data"]["C43"][0] / (data["Input Data"]["C26"][0] / data["Input Data"]["C41"][0]) / data["Input Data"]["C55"][0][0]'],
		'C71': [None, 'data["Input Data"]["C70"][0] / 60 / 6.28'],
		'C72': [None, 'data["Input Data"]["C67"][0] / data["Input Data"]["C69"][0]'],
		'C73': [None, 'data["Input Data"]["C72"][0] * 60 / 6.28'],
		'C74': [None, 'data["Input Data"]["C32"][0] * pi / 180'],
		'C75': [None, ' data["Input Data"]["C35"][0] * pi / 180'],
		'C78': [None, 'data["Input Data"]["C79"][0] * 180 / pi'],
		'C79': [None, 'acos(data["Input Data"]["C70"][0] / data["Input Data"]["C72"][0])'],
		'C80': [None, 'data["Input Data"]["C26"][0] / data["Input Data"]["C41"][0]'],
		'C81': [None, 'data["Input Data"]["Scarp angle"][0] / data["Input Data"]["C61"][0]'],
		'C82': [None, 'ceil(data["Input Data"]["C81"][0])'],
		'C84': [None, '0'],
		'C85': [None, 'data["Input Data"]["C62"][0] if data["Input Data"]["C82"][0] >=2 else "n.a."'],
		'C86': [None, 'data["Input Data"]["C62"][0] * 2 if data["Input Data"]["C82"][0] >=3 else "n.a."'],
		'C87': [None, 'data["Input Data"]["C62"][0] * 3 if data["Input Data"]["C82"][0] >=4 else "n.a."'],
		'J4': [None, 'acos(data["Input Data"]["C8"][0] / 2 - data["Input Data"]["C80"][0]) / (data["Input Data"]["C8"][0] / 2) if data["Input Data"]["C8"][0] >= data["Input Data"]["C80"][0] else pi / 2 + asin((data["Input Data"]["C80"][0] - data["Input Data"]["C8"][0] / 2) / (data["Input Data"]["C8"][0] / 2)) '],
		'J5': [None, 'data["Input Data"]["J4"][0] * 180 / pi'],
		'K5': [None, '"ok" if data["Input Data"]["J5"][0] <110 and if data["Input Data"]["J5"][0] < 720 / data["Input Data"]["C10"][0] else "verify"'],
		'J6': [None, 'data["Input Data"]["C59"][0] / (data["Input Data"]["C8"][0] / 2 * 9.81) ** (1 / 2)'],
		'K6': [None, '"ok" if 0.2<data["Input Data"]["J6"][0]<0.7 else "verify"'],
		'J7': [None, '(9.81 * data["Input Data"]["C8"][0] / 2) ** 0.5'],
		'J8': [None, 'data["Input Data"]["C59"][0] / data["Input Data"]["J7"][0]'],
		'K8': [None, '"BW speed increasable" if data["Input Data"]["J8"][0] < 0.5 else "it is necessary to decrease BW speed" if data["Input Data"]["J8"][0] > 0.6 else "ok, value between 0,5-0,6"'],
		'J9': [None, 'data["Input Data"]["C57"][0] / 3600 / data["Input Data"]["C65"][0]'],
		'K9': [None, '"ok" if data["Input Data"]["C11"][0] > data["Input Data"]["J9"][0] / data["Input Data"]["C17"][0] else "verify"'],
		'J10': [None, 'data["Input Data"]["C17"][0] * data["Input Data"]["C10"][0] * data["Input Data"]["C11"][0]'],
		'J11': [None, 'data["Input Data"]["C11"][0] ** (1/3) / data["Input Data"]["C66"][0]'],
		'K11': [None, '"ok" if 0.24 < data["Input Data"]["J11"][0] < 0.4 else "verify" '],
		'J12': [None, 'data["Input Data"]["C26"][0] / data["Input Data"]["C8"][0] * 2'],
		'J13': [None, 'data["Input Data"]["C80"][0] / data["Input Data"]["C8"][0] * 2'],
		'K13': [None, '"ok" if 1 < data["Input Data"]["J13"][0] < 1.44 else "verify"'],
		'J14': [None, 'data["Input Data"]["C43"][0] * cos(data["Input Data"]["C75"][0]) * sin(data["Input Data"]["C46"][0])'],
		'K14': [None, '"ok" if data["Input Data"]["C12"][0] > data["Input Data"]["J14"][0] else "verify"'],
		'J15': [None, 'data["Input Data"]["C67"][0] / data["Input Data"]["C65"][0]'],
		'K15': [None, '"ok" if data["Input Data"]["C13"][0] >= data["Input Data"]["J15"][0] else "verify"'],
	},
	'PRINT': {
		'K48': [None, 'data["Input Data"]["C6"][0]'],
		'J52': [None, 'data["Input Data"]["C2"][0]'],
		'M52': [None, 'data["Input Data"]["C3"][0]'],
		'O98': [None, 'data["Input Data"]["C6"][0]'],
		'L101': [None, 'data["Input Data"]["C2"][0]'],
		'O102': [None, 'data["Input Data"]["C3"][0]'],
		'O103': [None, 'data["Input Data"]["C4"][0]'],
		'O104': [None, 'data["Input Data"]["C5"][0]'],
		'O108': [None, 'data["Input Data"]["C27"][0]'],
		'O109': [None, 'data["Input Data"]["C26"][0]'],
		'O110': [None, 'data["Input Data"]["C29"][0]'],
		'O111': [None, 'data["Input Data"]["C28"][0]'],
		'O115': [None, 'data["Input Data"]["C8"][0]'],
		'O116': [None, 'data["Input Data"]["C10"][0]'],
		'O118': [None, 'data["Input Data"]["C12"][0]'],
		'O117': [None, 'data["Input Data"]["C11"][0]'],
		'O119': [None, 'data["Input Data"]["C13"][0]'],
		'O120': [None, 'data["Input Data"]["C9"][0]'],
		'O121': [None, 'data["Input Data"]["C16"][0]'],
		'O122': [None, 'data["Input Data"]["C17"][0]'],
		'O123': [None, 'data["Input Data"]["C18"][0]'],
		'O124': [None, 'data["Input Data"]["J6"][0]'],
		'O125': [None, 'data["Input Data"]["C64"][0]'],
		'O129': [None, 'data["Input Data"]["C20"][0]'],
		'O130': [None, 'data["Input Data"]["C24"][0]'],
		'O131': [None, 'data["Input Data"]["C21"][0]'],
		"O132": [None, 'data["Input Data"]["C22"][0]'],
		"O133": [None, 'data["Input Data"]["C23"][0]'],
		"O134": [None, 'data["Input Data"]["C15"][0]'],
		"O138": [None, 'data["Input Data"]["C25"][0]'],
		"O139": [None, 'data["Input Data"]["C36"][0]'],
		"O140": [None, 'data["Input Data"]["C38"][0]'],
		"O141": [None, 'data["Input Data"]["C41"][0]'],
		"O142": [None, 'data["Input Data"]["J13"][0]'],
		"O145": [None, 'data["Input Data"]["C42"][0]'],
		"O146": [None, 'data["Input Data"]["C32"][0]'],
		"O147": [None, 'data["Input Data"]["C35"][0]'],
		"B166": [None, 'data["Bench Analysis"]["B5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"C166": [None, 'data["Bench Analysis"]["G5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F166": [None, 'data["Bench Analysis"]["D5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I166": [None, 'data["Bench Analysis"]["W5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L166": [None, 'data["Bench Analysis"]["X5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B167": [None, 'data["Bench Analysis"]["B6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"C167": [None, 'data["Bench Analysis"]["G6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F167": [None, 'data["Bench Analysis"]["D6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I167": [None, 'data["Bench Analysis"]["W6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L167": [None, 'data["Bench Analysis"]["X6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"B168": [None, 'data["Bench Analysis"]["B7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"C168": [None, 'data["Bench Analysis"]["G7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F168": [None, 'data["Bench Analysis"]["D7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I168": [None, 'data["Bench Analysis"]["W7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L168": [None, 'data["Bench Analysis"]["X7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"B169": [None, 'data["Bench Analysis"]["B8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"C169": [None, 'data["Bench Analysis"]["G8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F169": [None, 'data["Bench Analysis"]["D8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I169": [None, 'data["Bench Analysis"]["W8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L169": [None, 'data["Bench Analysis"]["X8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"B170": [None, 'data["Bench Analysis"]["B9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"C170": [None, 'data["Bench Analysis"]["G9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F170": [None, 'data["Bench Analysis"]["D9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I170": [None, 'data["Bench Analysis"]["W9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L170": [None, 'data["Bench Analysis"]["X9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"B171": [None, 'data["Bench Analysis"]["B10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"C171": [None, 'data["Bench Analysis"]["G10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F171": [None, 'data["Bench Analysis"]["D10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I171": [None, 'data["Bench Analysis"]["W10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L171": [None, 'data["Bench Analysis"]["X10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"B172": [None, 'data["Bench Analysis"]["B11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"C172": [None, 'data["Bench Analysis"]["G11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F172": [None, 'data["Bench Analysis"]["D11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I172": [None, 'data["Bench Analysis"]["W11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L172": [None, 'data["Bench Analysis"]["X11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"B173": [None, 'data["Bench Analysis"]["B12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"C173": [None, 'data["Bench Analysis"]["G12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F173": [None, 'data["Bench Analysis"]["D12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I173": [None, 'data["Bench Analysis"]["W12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L173": [None, 'data["Bench Analysis"]["X12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"B174": [None, 'data["Bench Analysis"]["B13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"C174": [None, 'data["Bench Analysis"]["G13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F174": [None, 'data["Bench Analysis"]["D13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I174": [None, 'data["Bench Analysis"]["W13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L174": [None, 'data["Bench Analysis"]["X13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"B175": [None, 'data["Bench Analysis"]["B14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"C175": [None, 'data["Bench Analysis"]["G14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F175": [None, 'data["Bench Analysis"]["D14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I175": [None, 'data["Bench Analysis"]["W14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L175": [None, 'data["Bench Analysis"]["X14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"B181": [None, 'data["PRINT"]["B166"][0]'],
		"C181": [None, 'data["Bench Analysis"]["H5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F181": [None, 'data["Bench Analysis"]["I5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I181": [None, 'data["Bench Analysis"]["J5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L181": [None, 'data["Bench Analysis"]["R5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"O181": [None, 'data["Bench Analysis"]["F5"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F5"][0] != "n.a." else ""'],
		"R181": [None, 'data["Bench Analysis"]["Z5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B182": [None, 'data["PRINT"]["B167"][0]'],
		"C182": [None, 'data["Bench Analysis"]["H6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F182": [None, 'data["Bench Analysis"]["I6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I182": [None, 'data["Bench Analysis"]["J6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L182": [None, 'data["Bench Analysis"]["R6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"O182": [None, 'data["Bench Analysis"]["F6"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F6"][0] != "n.a." else ""'],
		"R182": [None, 'data["Bench Analysis"]["Z6"][0] if data["Bench Analysis"]["Z6"][0] != "n.a." else ""'],
		"B183": [None, 'data["PRINT"]["B168"][0]'],
		"C183": [None, 'data["Bench Analysis"]["H7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F183": [None, 'data["Bench Analysis"]["I7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I183": [None, 'data["Bench Analysis"]["J7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L183": [None, 'data["Bench Analysis"]["R7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"O183": [None, 'data["Bench Analysis"]["F7"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F7"][0] != "n.a." else ""'],
		"R183": [None, 'data["Bench Analysis"]["Z7"][0] if data["Bench Analysis"]["Z7"][0] != "n.a." else ""'],
		"B184": [None, 'data["PRINT"]["B169"][0]'],
		"C184": [None, 'data["Bench Analysis"]["H8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F184": [None, 'data["Bench Analysis"]["I8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I184": [None, 'data["Bench Analysis"]["J8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L184": [None, 'data["Bench Analysis"]["R8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"O184": [None, 'data["Bench Analysis"]["F8"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F8"][0] != "n.a." else ""'],
		"R184": [None, 'data["Bench Analysis"]["Z8"][0] if data["Bench Analysis"]["Z8"][0] != "n.a." else ""'],
		"B185": [None, 'data["PRINT"]["B170"][0]'],
		"C185": [None, 'data["Bench Analysis"]["H9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F185": [None, 'data["Bench Analysis"]["I9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I185": [None, 'data["Bench Analysis"]["J9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L185": [None, 'data["Bench Analysis"]["R9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"O185": [None, 'data["Bench Analysis"]["F9"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F9"][0] != "n.a." else ""'],
		"R185": [None, 'data["Bench Analysis"]["Z9"][0] if data["Bench Analysis"]["Z9"][0] != "n.a." else ""'],
		"B186": [None, 'data["PRINT"]["B171"][0]'],
		"C186": [None, 'data["Bench Analysis"]["H10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F186": [None, 'data["Bench Analysis"]["I10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I186": [None, 'data["Bench Analysis"]["J10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L186": [None, 'data["Bench Analysis"]["R10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"O186": [None, 'data["Bench Analysis"]["F10"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F10"][0] != "n.a." else ""'],
		"R186": [None, 'data["Bench Analysis"]["Z10"][0] if data["Bench Analysis"]["Z10"][0] != "n.a." else ""'],
		"B187": [None, 'data["PRINT"]["B172"][0]'],
		"C187": [None, 'data["Bench Analysis"]["H11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F187": [None, 'data["Bench Analysis"]["I11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I187": [None, 'data["Bench Analysis"]["J11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L187": [None, 'data["Bench Analysis"]["R11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"O187": [None, 'data["Bench Analysis"]["F11"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F11"][0] != "n.a." else ""'],
		"R187": [None, 'data["Bench Analysis"]["Z11"][0] if data["Bench Analysis"]["Z11"][0] != "n.a." else ""'],
		"B188": [None, 'data["PRINT"]["B173"][0]'],
		"C188": [None, 'data["Bench Analysis"]["H12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F188": [None, 'data["Bench Analysis"]["I12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I188": [None, 'data["Bench Analysis"]["J12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L188": [None, 'data["Bench Analysis"]["R12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"O188": [None, 'data["Bench Analysis"]["F12"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F12"][0] != "n.a." else ""'],
		"R188": [None, 'data["Bench Analysis"]["Z12"][0] if data["Bench Analysis"]["Z12"][0] != "n.a." else ""'],
		"B189": [None, 'data["PRINT"]["B174"][0]'],
		"C189": [None, 'data["Bench Analysis"]["H13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F189": [None, 'data["Bench Analysis"]["I13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I189": [None, 'data["Bench Analysis"]["J13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L189": [None, 'data["Bench Analysis"]["R13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"O189": [None, 'data["Bench Analysis"]["F13"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F13"][0] != "n.a." else ""'],
		"R189": [None, 'data["Bench Analysis"]["Z13"][0] if data["Bench Analysis"]["Z13"][0] != "n.a." else ""'],
		"B190": [None, 'data["PRINT"]["B175"][0]'],
		"C190": [None, 'data["Bench Analysis"]["H14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F190": [None, 'data["Bench Analysis"]["I14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I190": [None, 'data["Bench Analysis"]["J14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L190": [None, 'data["Bench Analysis"]["R14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"O190": [None, 'data["Bench Analysis"]["F14"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F14"][0] != "n.a." else ""'],
		"R190": [None, 'data["Bench Analysis"]["Z14"][0] if data["Bench Analysis"]["Z14"][0] != "n.a." else ""'],
	},
}

# for the materials I don't use a dictionary of list because the values are constants, so is better to use a tuple
materials = \
{
	'ore': (22.7456, 0.4, 35, 0.4),
	'coal': (8.743, 0.35, None, 0.35),
	'pellet': (13.1194, 0.3, (30, 44), 0.35),
	'coke': (17.4959, 0.25, None, 0.25),
    'limestone': (17.4959, 0.5, (30, 44), 0.5)
}
