# IMPORTS
from math import pi, tan, asin, cos, sin, acos, ceil

data = \
{
	'Input Data': {
		'C2': [None, '-', 'Material'],
		'C3': [None, 'r [t/m3]', 'Bulk density'],
		'C4': [None, 'f [°]', 'Repose angle'],
		'C5': [None, 'materials[data["Input Data"]["C2"][0]'],
		'C6': [None, 'Q [t/h]', 'Nominal Required Capacity[0]'],
		'C7': [None, 'data["Input Data"]["C6"][0] / data["Input Data"]["C3"][0] / 3600'],
		'C8': [None, 'D [m]', 'Diameter (on cutting edge)'],
		'C9': [None, 'wBW [rpm]', 'Bucket wheel rotational speed'],
		'C10': [None, 'z', 'Number of buckets'],
		'C11': [None, 'Vb [m3] ', 'Bucket volume'],
		'C12': [None, 'tE [m]', 'Bucket height'],
		'C13': [None, 'bE [m]', 'Bucket width'],
		'C14': [None, '1.24 * pi / 4 * data["Input Data"]["C12"][0] ** 2 * data["Input Data"]["C13"][0]'],
		'C15': [None, 'θ [°]', 'Angle in which bucket discharge starts, measured from vert'],
		'C16': [None, 'm ', 'Efficiency of Drive (Coupling+Motor+Gearbox)'],
		'C17': [None, 'f', 'Bucket Efficiency (filling factor)'],
		'C18': [None, 'data["Input Data"]["C17"][0] * data["Input Data"]["C3"][0] * data["Input Data"]["C11"][0] * data["Input Data"]["C65"][0] * 3600'],
		'C19': [None, 'data["Input Data"]["C18"][0] / data["Input Data"]["C3"][0] / 3600'],
		'C20': [None, 'Lb [m]', 'Boom Lenght'],
		'C21': [None, 'HL [m]', 'Height of boom hinge from bottom of yard'],
		'C22': [None, 'l [m]', 'Distance of boom hinge from slewing axle'],
		'C23': [None, 'h  [m]', 'Height of BW axle from boom hinge (with boom horizontal)'],
		'C24': [None, 'd [m]', 'Distance between pile CL and slewing axle'],
		'C25': [None, 'vSmax  [m/min]', 'Maximum selected boom slewing speed'],
		'C26': [None, 'Hp [m]', 'Stockpile height'],
		'C27': [None, 'Bp [m]', 'Bottom stockpile width'],
		'C28': [None, 'Lp [m]', 'Stockpile lenght (of the full stockpile section)'],
		'C29': [None, 'data["Input Data"]["C27"][0] - 2 * data["Input Data"]["C26"][0] / tan(data["Input Data"]["C47"][0])'],
		'C30': [None, 'asin((data["Input Data"]["C24"][0] - data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0])'],
		'C31': [None, 'data["Input Data"]["C30"][0] * 180 / pi'],
		'C32': [None, 'data["Input Data"]["C31"][0][0]'],
		'C33': [None, 'pi / 2 if (data["Input Data"]["C24"][0] + data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0] < 1 else asin((data["Input Data"]["C24"][0] + data["Input Data"]["C27"][0] / 2) / data["Input Data"]["C55"][0][0])'],
		'C34': [None, 'data["Input Data"]["C33"][0] * 180 / pi'],
		'C35': [None, 'ymax [°]', 'Selected Maximum angle of Reclaiming (in plant view)'],
		'C36': [None, 'a1 [°/s2]', 'Slewing acceleration[0]'],
		'C37': [None, 'data["Input Data"]["C36"][0] * pi / 180'],
		'C38': [None, 'a2 [°/s2]', 'Slewing deceleration[0]'],
		'C39': [None, 'data["Input Data"]["C38"][0] * pi / 180'],
		'C40': [None, 'data["Input Data"]["Stockpile height"] / data["Input Data"]["C8"][0] * 2'],
		'C41': [None, '-', 'Number of selected benches'],
		'C42': [None, 'data["Input Data"]["C12"][0] / cos(data["Input Data"]["C75"][0])'],
		'C43': [None, 'p [m]', 'Selected Step of Reclaiming[0]'],
		'C44': [None, 'data["Input Data"]["C15"][0]'],
		'C46': [None, 'materials[data["Input Data"]["C2"][0]][1]'],
		'C47': [None, 'data["Input Data"]["C4"][0] * pi / 180'],
		'C48': [None, 'materials[data["Input Data"]["C2"][0]][0]'],
		'C51': [None, 'data["Input Data"]["C52"][0] * 180 / pi'],
		'C52': [None, 'asin((0.98 * data["Input Data"]["C23"][0] + data["Input Data"]["C21"][0] - data["Input Data"]["C8"][0] / 2) / data["Input Data"]["C20"][0] '],
		'C53': [None, 'data["Input Data"]["Maximum luffing angle"][0] * 180 / pi'],
		'C54': [None, 'asin((data["Input Data"]["C26"][0] - data["Input Data"]["C21"][0] - 0.985 *  data["Input Data"]["C23"][0] + data["Input Data"]["C8"][0] / 2) / data["Input Data"]["C20"][0]) '],
		'C55': [None, 'data["Input Data"]["C22"][0] + data["Input Data"]["C20"][0] * cos(data["Input Data"]["C52"][0]) + data["Input Data"]["C23"][0] * sin(data["Input Data"]["C52"][0]) + data["Input Data"]["C8"][0] / 2 * sin(data["Input Data"]["C47"][0])'],
		'C57': [None, 'data["Input Data"]["C6"][0] / data["Input Data"]["C3"][0] / data["Input Data"]["C17"][0]'],
		'C58': [None, 'data["Input Data"]["C9"][0] * 2 * pi / 60'],
		'C59': [None, 'data["Input Data"]["Rotational speed"][0] * data["Input Data"]["C8"][0] / 2'],
		'C60': [None, 'data["Input Data"]["C59"][0] * 60'],
		'C61': [None, '2 * pi  / data["Input Data"]["C10"][0]'],
		'C62': [None, '360 / data["Input Data"]["C10"][0]'],
		'C63': [None, '60 / data["Input Data"]["C9"][0] / data["Input Data"]["C10"][0]'],
		'C64': [None, 'data["Input Data"]["C9"][0] * data["Input Data"]["C10"][0]'],
		'C65': [None, 'data["Input Data"]["C64"][0] / 60'],
		'C66': [None, '3.14 * data["Input Data"]["C8"][0] / data["Input Data"]["C10"][0]'],
		'C67': [None, 'data["Input Data"]["C25"][0] / 60'],
		'C68': [None, 'data["Input Data"]["C70"][0] * data["Input Data"]["C69"][0]'],
		'C69': [None, 'data["Input Data"]["C20"][0] + data["Input Data"]["C8"][0] / 2 * sin(data["Input Data"]["C5"][0]) + data["Input Data"]["C22"][0]'],
		'C70': [None, 'data["Input Data"]["C11"][0] * data["Input Data"]["C17"][0] * data["Input Data"]["C65"][0] / data["Input Data"]["C43"][0] / (data["Input Data"]["C26"][0] / data["Input Data"]["C41"][0]) / data["Input Data"]["C55"][0][0]'],
		'C71': [None, 'data["Input Data"]["C70"][0] / 60 / 6.28'],
		'C72': [None, 'data["Input Data"]["C67"][0] / data["Input Data"]["C69"][0]'],
		'C73': [None, 'data["Input Data"]["C72"][0] * 60 / 6.28'],
		'C74': [None, 'data["Input Data"]["C32"][0] * pi / 180'],
		'C75': [None, ' data["Input Data"]["C35"][0] * pi / 180'],
		'C78': [None, 'data["Input Data"]["C79"][0] * 180 / pi'],
		'C79': [None, 'acos(data["Input Data"]["C70"][0] / data["Input Data"]["C72"][0])'],
		'C80': [None, 'data["Input Data"]["C26"][0] / data["Input Data"]["C41"][0]'],
		'C81': [None, 'data["Input Data"]["Scarp angle"][0] / data["Input Data"]["C61"][0]'],
		'C82': [None, 'ceil(data["Input Data"]["C81"][0])'],
		'C84': [None, '0'],
		'C85': [None, 'data["Input Data"]["C62"][0] if data["Input Data"]["C82"][0] >=2 else "n.a."'],
		'C86': [None, 'data["Input Data"]["C62"][0] * 2 if data["Input Data"]["C82"][0] >=3 else "n.a."'],
		'C87': [None, 'data["Input Data"]["C62"][0] * 3 if data["Input Data"]["C82"][0] >=4 else "n.a."'],
		'J4': [None, 'acos(data["Input Data"]["C8"][0] / 2 - data["Input Data"]["C80"][0]) / (data["Input Data"]["C8"][0] / 2) if data["Input Data"]["C8"][0] >= data["Input Data"]["C80"][0] else pi / 2 + asin((data["Input Data"]["C80"][0] - data["Input Data"]["C8"][0] / 2) / (data["Input Data"]["C8"][0] / 2)) '],
		'J5': [None, 'data["Input Data"]["J4"][0] * 180 / pi'],
		'K5': [None, '"ok" if data["Input Data"]["J5"][0] <110 and if data["Input Data"]["J5"][0] < 720 / data["Input Data"]["C10"][0] else "verify"'],
		'J6': [None, 'data["Input Data"]["C59"][0] / (data["Input Data"]["C8"][0] / 2 * 9.81) ** (1 / 2)'],
		'K6': [None, '"ok" if 0.2<data["Input Data"]["J6"][0]<0.7 else "verify"'],
		'J7': [None, '(9.81 * data["Input Data"]["C8"][0] / 2) ** 0.5'],
		'J8': [None, 'data["Input Data"]["C59"][0] / data["Input Data"]["J7"][0]'],
		'K8': [None, '"BW speed increasable" if data["Input Data"]["J8"][0] < 0.5 else "it is necessary to decrease BW speed" if data["Input Data"]["J8"][0] > 0.6 else "ok, value between 0,5-0,6"'],
		'J9': [None, 'data["Input Data"]["C57"][0] / 3600 / data["Input Data"]["C65"][0]'],
		'K9': [None, '"ok" if data["Input Data"]["C11"][0] > data["Input Data"]["J9"][0] / data["Input Data"]["C17"][0] else "verify"'],
		'J10': [None, 'data["Input Data"]["C17"][0] * data["Input Data"]["C10"][0] * data["Input Data"]["C11"][0]'],
		'J11': [None, 'data["Input Data"]["C11"][0] ** (1/3) / data["Input Data"]["C66"][0]'],
		'K11': [None, '"ok" if 0.24 < data["Input Data"]["J11"][0] < 0.4 else "verify" '],
		'J12': [None, 'data["Input Data"]["C26"][0] / data["Input Data"]["C8"][0] * 2'],
		'J13': [None, 'data["Input Data"]["C80"][0] / data["Input Data"]["C8"][0] * 2'],
		'K13': [None, '"ok" if 1 < data["Input Data"]["J13"][0] < 1.44 else "verify"'],
		'J14': [None, 'data["Input Data"]["C43"][0] * cos(data["Input Data"]["C75"][0]) * sin(data["Input Data"]["C46"][0])'],
		'K14': [None, '"ok" if data["Input Data"]["C12"][0] > data["Input Data"]["J14"][0] else "verify"'],
		'J15': [None, 'data["Input Data"]["C67"][0] / data["Input Data"]["C65"][0]'],
		'K15': [None, '"ok" if data["Input Data"]["C13"][0] >= data["Input Data"]["J15"][0] else "verify"'],
	},
	'PRINT': {
		'K48': [None, 'data["Input Data"]["C6"][0]'],
		'J52': [None, 'data["Input Data"]["C2"][0]'],
		'M52': [None, 'data["Input Data"]["C3"][0]'],
		'O98': [None, 'data["Input Data"]["C6"][0]'],
		'L101': [None, 'data["Input Data"]["C2"][0]'],
		'O102': [None, 'data["Input Data"]["C3"][0]'],
		'O103': [None, 'data["Input Data"]["C4"][0]'],
		'O104': [None, 'data["Input Data"]["C5"][0]'],
		'O108': [None, 'data["Input Data"]["C27"][0]'],
		'O109': [None, 'data["Input Data"]["C26"][0]'],
		'O110': [None, 'data["Input Data"]["C29"][0]'],
		'O111': [None, 'data["Input Data"]["C28"][0]'],
		'O115': [None, 'data["Input Data"]["C8"][0]'],
		'O116': [None, 'data["Input Data"]["C10"][0]'],
		'O118': [None, 'data["Input Data"]["C12"][0]'],
		'O117': [None, 'data["Input Data"]["C11"][0]'],
		'O119': [None, 'data["Input Data"]["C13"][0]'],
		'O120': [None, 'data["Input Data"]["C9"][0]'],
		'O121': [None, 'data["Input Data"]["C16"][0]'],
		'O122': [None, 'data["Input Data"]["C17"][0]'],
		'O123': [None, 'data["Input Data"]["C18"][0]'],
		'O124': [None, 'data["Input Data"]["J6"][0]'],
		'O125': [None, 'data["Input Data"]["C64"][0]'],
		'O129': [None, 'data["Input Data"]["C20"][0]'],
		'O130': [None, 'data["Input Data"]["C24"][0]'],
		'O131': [None, 'data["Input Data"]["C21"][0]'],
		"O132": [None, 'data["Input Data"]["C22"][0]'],
		"O133": [None, 'data["Input Data"]["C23"][0]'],
		"O134": [None, 'data["Input Data"]["C15"][0]'],
		"O138": [None, 'data["Input Data"]["C25"][0]'],
		"O139": [None, 'data["Input Data"]["C36"][0]'],
		"O140": [None, 'data["Input Data"]["C38"][0]'],
		"O141": [None, 'data["Input Data"]["C41"][0]'],
		"O142": [None, 'data["Input Data"]["J13"][0]'],
		"O145": [None, 'data["Input Data"]["C42"][0]'],
		"O146": [None, 'data["Input Data"]["C32"][0]'],
		"O147": [None, 'data["Input Data"]["C35"][0]'],
		"B166": [None, 'data["Bench Analysis"]["B5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"C166": [None, 'data["Bench Analysis"]["G5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F166": [None, 'data["Bench Analysis"]["D5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I166": [None, 'data["Bench Analysis"]["W5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L166": [None, 'data["Bench Analysis"]["X5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B167": [None, 'data["Bench Analysis"]["B6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"C167": [None, 'data["Bench Analysis"]["G6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F167": [None, 'data["Bench Analysis"]["D6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I167": [None, 'data["Bench Analysis"]["W6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L167": [None, 'data["Bench Analysis"]["X6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"B168": [None, 'data["Bench Analysis"]["B7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"C168": [None, 'data["Bench Analysis"]["G7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F168": [None, 'data["Bench Analysis"]["D7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I168": [None, 'data["Bench Analysis"]["W7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L168": [None, 'data["Bench Analysis"]["X7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"B169": [None, 'data["Bench Analysis"]["B8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"C169": [None, 'data["Bench Analysis"]["G8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F169": [None, 'data["Bench Analysis"]["D8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I169": [None, 'data["Bench Analysis"]["W8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L169": [None, 'data["Bench Analysis"]["X8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"B170": [None, 'data["Bench Analysis"]["B9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"C170": [None, 'data["Bench Analysis"]["G9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F170": [None, 'data["Bench Analysis"]["D9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I170": [None, 'data["Bench Analysis"]["W9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L170": [None, 'data["Bench Analysis"]["X9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"B171": [None, 'data["Bench Analysis"]["B10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"C171": [None, 'data["Bench Analysis"]["G10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F171": [None, 'data["Bench Analysis"]["D10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I171": [None, 'data["Bench Analysis"]["W10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L171": [None, 'data["Bench Analysis"]["X10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"B172": [None, 'data["Bench Analysis"]["B11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"C172": [None, 'data["Bench Analysis"]["G11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F172": [None, 'data["Bench Analysis"]["D11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I172": [None, 'data["Bench Analysis"]["W11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L172": [None, 'data["Bench Analysis"]["X11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"B173": [None, 'data["Bench Analysis"]["B12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"C173": [None, 'data["Bench Analysis"]["G12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F173": [None, 'data["Bench Analysis"]["D12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I173": [None, 'data["Bench Analysis"]["W12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L173": [None, 'data["Bench Analysis"]["X12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"B174": [None, 'data["Bench Analysis"]["B13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"C174": [None, 'data["Bench Analysis"]["G13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F174": [None, 'data["Bench Analysis"]["D13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I174": [None, 'data["Bench Analysis"]["W13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L174": [None, 'data["Bench Analysis"]["X13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"B175": [None, 'data["Bench Analysis"]["B14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"C175": [None, 'data["Bench Analysis"]["G14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F175": [None, 'data["Bench Analysis"]["D14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I175": [None, 'data["Bench Analysis"]["W14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L175": [None, 'data["Bench Analysis"]["X14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"B181": [None, 'data["PRINT"]["B166"][0]'],
		"C181": [None, 'data["Bench Analysis"]["H5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F181": [None, 'data["Bench Analysis"]["I5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I181": [None, 'data["Bench Analysis"]["J5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L181": [None, 'data["Bench Analysis"]["R5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"O181": [None, 'data["Bench Analysis"]["F5"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F5"][0] != "n.a." else ""'],
		"R181": [None, 'data["Bench Analysis"]["Z5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B182": [None, 'data["PRINT"]["B167"][0]'],
		"C182": [None, 'data["Bench Analysis"]["H6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F182": [None, 'data["Bench Analysis"]["I6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I182": [None, 'data["Bench Analysis"]["J6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L182": [None, 'data["Bench Analysis"]["R6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"O182": [None, 'data["Bench Analysis"]["F6"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F6"][0] != "n.a." else ""'],
		"R182": [None, 'data["Bench Analysis"]["Z6"][0] if data["Bench Analysis"]["Z6"][0] != "n.a." else ""'],
		"B183": [None, 'data["PRINT"]["B168"][0]'],
		"C183": [None, 'data["Bench Analysis"]["H7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F183": [None, 'data["Bench Analysis"]["I7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I183": [None, 'data["Bench Analysis"]["J7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L183": [None, 'data["Bench Analysis"]["R7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"O183": [None, 'data["Bench Analysis"]["F7"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F7"][0] != "n.a." else ""'],
		"R183": [None, 'data["Bench Analysis"]["Z7"][0] if data["Bench Analysis"]["Z7"][0] != "n.a." else ""'],
		"B184": [None, 'data["PRINT"]["B169"][0]'],
		"C184": [None, 'data["Bench Analysis"]["H8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F184": [None, 'data["Bench Analysis"]["I8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I184": [None, 'data["Bench Analysis"]["J8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L184": [None, 'data["Bench Analysis"]["R8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"O184": [None, 'data["Bench Analysis"]["F8"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F8"][0] != "n.a." else ""'],
		"R184": [None, 'data["Bench Analysis"]["Z8"][0] if data["Bench Analysis"]["Z8"][0] != "n.a." else ""'],
		"B185": [None, 'data["PRINT"]["B170"][0]'],
		"C185": [None, 'data["Bench Analysis"]["H9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F185": [None, 'data["Bench Analysis"]["I9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I185": [None, 'data["Bench Analysis"]["J9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L185": [None, 'data["Bench Analysis"]["R9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"O185": [None, 'data["Bench Analysis"]["F9"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F9"][0] != "n.a." else ""'],
		"R185": [None, 'data["Bench Analysis"]["Z9"][0] if data["Bench Analysis"]["Z9"][0] != "n.a." else ""'],
		"B186": [None, 'data["PRINT"]["B171"][0]'],
		"C186": [None, 'data["Bench Analysis"]["H10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F186": [None, 'data["Bench Analysis"]["I10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I186": [None, 'data["Bench Analysis"]["J10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L186": [None, 'data["Bench Analysis"]["R10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"O186": [None, 'data["Bench Analysis"]["F10"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F10"][0] != "n.a." else ""'],
		"R186": [None, 'data["Bench Analysis"]["Z10"][0] if data["Bench Analysis"]["Z10"][0] != "n.a." else ""'],
		"B187": [None, 'data["PRINT"]["B172"][0]'],
		"C187": [None, 'data["Bench Analysis"]["H11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F187": [None, 'data["Bench Analysis"]["I11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I187": [None, 'data["Bench Analysis"]["J11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L187": [None, 'data["Bench Analysis"]["R11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"O187": [None, 'data["Bench Analysis"]["F11"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F11"][0] != "n.a." else ""'],
		"R187": [None, 'data["Bench Analysis"]["Z11"][0] if data["Bench Analysis"]["Z11"][0] != "n.a." else ""'],
		"B188": [None, 'data["PRINT"]["B173"][0]'],
		"C188": [None, 'data["Bench Analysis"]["H12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F188": [None, 'data["Bench Analysis"]["I12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I188": [None, 'data["Bench Analysis"]["J12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L188": [None, 'data["Bench Analysis"]["R12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"O188": [None, 'data["Bench Analysis"]["F12"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F12"][0] != "n.a." else ""'],
		"R188": [None, 'data["Bench Analysis"]["Z12"][0] if data["Bench Analysis"]["Z12"][0] != "n.a." else ""'],
		"B189": [None, 'data["PRINT"]["B174"][0]'],
		"C189": [None, 'data["Bench Analysis"]["H13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F189": [None, 'data["Bench Analysis"]["I13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I189": [None, 'data["Bench Analysis"]["J13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L189": [None, 'data["Bench Analysis"]["R13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"O189": [None, 'data["Bench Analysis"]["F13"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F13"][0] != "n.a." else ""'],
		"R189": [None, 'data["Bench Analysis"]["Z13"][0] if data["Bench Analysis"]["Z13"][0] != "n.a." else ""'],
		"B190": [None, 'data["PRINT"]["B175"][0]'],
		"C190": [None, 'data["Bench Analysis"]["H14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F190": [None, 'data["Bench Analysis"]["I14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I190": [None, 'data["Bench Analysis"]["J14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L190": [None, 'data["Bench Analysis"]["R14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"O190": [None, 'data["Bench Analysis"]["F14"][0] / data["Input Data"]["C8"][0] * 2 if data["Bench Analysis"]["F14"][0] != "n.a." else ""'],
		"R190": [None, 'data["Bench Analysis"]["Z14"][0] if data["Bench Analysis"]["Z14"][0] != "n.a." else ""'],
    
		"B196": [None, 'data["PRINT"]["B181"][0]'],
		"C196": [None, 'data["Bench Analysis"]["Y5"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F196": [None, 'data["Bench Analysis"]["AA5"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I196": [None, 'data["Bench Analysis"]["AC5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L196": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R5"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"O196": [None, 'data["PRINT"]["L196"][0]  * data["PRINT"]["O240"][0] / 3600 if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B197": [None, 'data["PRINT"]["B182"][0]'],
		"C197": [None, 'data["Bench Analysis"]["Y6"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F197": [None, 'data["Bench Analysis"]["AA6"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I197": [None, 'data["Bench Analysis"]["AC6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L197": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R6"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"O197": [None, 'data["PRINT"]["L197"][0]  * data["PRINT"]["O241"][0] / 3600 if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"B198": [None, 'data["PRINT"]["B183"][0]'],
		"C198": [None, 'data["Bench Analysis"]["Y7"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F198": [None, 'data["Bench Analysis"]["AA7"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I198": [None, 'data["Bench Analysis"]["AC7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L198": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R7"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"O198": [None, 'data["PRINT"]["L198"][0]  * data["PRINT"]["O242"][0] / 3600 if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"B199": [None, 'data["PRINT"]["B184"][0]'],
		"C199": [None, 'data["Bench Analysis"]["Y8"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F199": [None, 'data["Bench Analysis"]["AA8"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I199": [None, 'data["Bench Analysis"]["AC8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L199": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R8"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"O199": [None, 'data["PRINT"]["L199"][0]  * data["PRINT"]["O243"][0] / 3600 if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"B200": [None, 'data["PRINT"]["B185"][0]'],
		"C200": [None, 'data["Bench Analysis"]["Y9"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F200": [None, 'data["Bench Analysis"]["AA9"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I200": [None, 'data["Bench Analysis"]["AC9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L200": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R9"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"O200": [None, 'data["PRINT"]["L200"][0]  * data["PRINT"]["O244"][0] / 3600 if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"B201": [None, 'data["PRINT"]["B186"][0]'],
		"C201": [None, 'data["Bench Analysis"]["Y10"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F201": [None, 'data["Bench Analysis"]["AA10"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I201": [None, 'data["Bench Analysis"]["AC10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L201": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R10"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"O201": [None, 'data["PRINT"]["L201"][0]  * data["PRINT"]["O245"][0] / 3600 if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"B202": [None, 'data["PRINT"]["B187"][0]'],
		"C202": [None, 'data["Bench Analysis"]["Y11"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F202": [None, 'data["Bench Analysis"]["AA11"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I202": [None, 'data["Bench Analysis"]["AC11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L202": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R11"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"O202": [None, 'data["PRINT"]["L202"][0]  * data["PRINT"]["O246"][0] / 3600 if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"B203": [None, 'data["PRINT"]["B188"][0]'],
		"C203": [None, 'data["Bench Analysis"]["Y12"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F203": [None, 'data["Bench Analysis"]["AA12"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I203": [None, 'data["Bench Analysis"]["AC12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L203": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R12"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"O203": [None, 'data["PRINT"]["L203"][0]  * data["PRINT"]["O247"][0] / 3600 if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"B204": [None, 'data["PRINT"]["B189"][0]'],
		"C204": [None, 'data["Bench Analysis"]["Y13"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F204": [None, 'data["Bench Analysis"]["AA13"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I204": [None, 'data["Bench Analysis"]["AC13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L204": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R13"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"O204": [None, 'data["PRINT"]["L204"][0]  * data["PRINT"]["O248"][0] / 3600 if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"B205": [None, 'data["PRINT"]["B190"][0]'],
		"C205": [None, 'data["Bench Analysis"]["Y14"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F205": [None, 'data["Bench Analysis"]["AA14"][0] * data["Input Data"]["C3"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I205": [None, 'data["Bench Analysis"]["AC14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L205": [None, 'data["Input Data"]["C28"][0] / data["Bench Analysis"]["R14"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"O205": [None, 'data["PRINT"]["L205"][0]  * data["PRINT"]["O249"][0] / 3600 if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"K210": [None, 'sum([data["PRINT"][f"C{i}"][0] for i in range(196,206])'],
		"K211": [None, 'sum([data["PRINT"]["f"F{i}""][0] for i in range(196,206])'],
		"K212": [None, 'data["Bench Analysis"]["AC15"][0]'],
		"K213": [None, 'data["Bench Analysis"]["AA18"][0]'],
		"B240": [None, 'data["PRINT"]["B196"][0]'],
		"C240": [None, 'data["Bench Analysis"]["C22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F240": [None, 'data["Bench Analysis"]["D22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I240": [None, 'data["Bench Analysis"]["H22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L240": [None, 'data["Bench Analysis"]["I22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"O240": [None, 'data["Bench-1"]["D186"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B241": [None, 'data["PRINT"]["B197"][0]'],
		"C241": [None, 'data["Bench Analysis"]["C23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F241": [None, 'data["Bench Analysis"]["D23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I241": [None, 'data["Bench Analysis"]["H23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L241": [None, 'data["Bench Analysis"]["I23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"O241": [None, 'data["Bench-2"]["D186"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"B242": [None, 'data["PRINT"]["B198"][0]'],
		"C242": [None, 'data["Bench Analysis"]["C24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F242": [None, 'data["Bench Analysis"]["D24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I242": [None, 'data["Bench Analysis"]["H24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L242": [None, 'data["Bench Analysis"]["I24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"O242": [None, 'data["Bench-3"]["D186"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"B243": [None, 'data["PRINT"]["B199"][0]'],
		"C243": [None, 'data["Bench Analysis"]["C25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F243": [None, 'data["Bench Analysis"]["D25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I243": [None, 'data["Bench Analysis"]["H25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L243": [None, 'data["Bench Analysis"]["I25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"O243": [None, 'data["Bench-4"]["D186"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"B244": [None, 'data["PRINT"]["B200"][0]'],
		"C244": [None, 'data["Bench Analysis"]["C26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F244": [None, 'data["Bench Analysis"]["D26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I244": [None, 'data["Bench Analysis"]["H26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L244": [None, 'data["Bench Analysis"]["I26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"O244": [None, 'data["Bench-5"]["D186"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"B245": [None, 'data["PRINT"]["B201"][0]'],
		"C245": [None, 'data["Bench Analysis"]["C27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F245": [None, 'data["Bench Analysis"]["D27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I245": [None, 'data["Bench Analysis"]["H27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L245": [None, 'data["Bench Analysis"]["I27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"O245": [None, 'data["Bench-6"]["D186"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"B246": [None, 'data["PRINT"]["B202"][0]'],
		"C246": [None, 'data["Bench Analysis"]["C28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F246": [None, 'data["Bench Analysis"]["D28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I246": [None, 'data["Bench Analysis"]["H28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L246": [None, 'data["Bench Analysis"]["I28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"O246": [None, 'data["Bench-7"]["D186"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"B247": [None, 'data["PRINT"]["B203"][0]'],
		"C247": [None, 'data["Bench Analysis"]["C29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F247": [None, 'data["Bench Analysis"]["D29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I247": [None, 'data["Bench Analysis"]["H29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L247": [None, 'data["Bench Analysis"]["I29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"O247": [None, 'data["Bench-8"]["D186"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"B248": [None, 'data["PRINT"]["B204"][0]'],
		"C248": [None, 'data["Bench Analysis"]["C30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F248": [None, 'data["Bench Analysis"]["D30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I248": [None, 'data["Bench Analysis"]["H30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L248": [None, 'data["Bench Analysis"]["I30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"O248": [None, 'data["Bench-9"]["D186"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"B249": [None, 'data["PRINT"]["B205"][0]'],
		"C249": [None, 'data["Bench Analysis"]["C31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F249": [None, 'data["Bench Analysis"]["D31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I249": [None, 'data["Bench Analysis"]["H31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L249": [None, 'data["Bench Analysis"]["I31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"O249": [None, 'data["Bench-10"]["D186"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"B264": [None, 'data["PRINT"]["B240"][0]'],
		"C264": [None, 'data["Bench Analysis"]["J22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"F264": [None, 'data["Bench Analysis"]["K22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"I264": [None, 'data["Bench Analysis"]["R22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"L264": [None, 'data["Bench Analysis"]["S22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"O264": [None, 'data["Bench Analysis"]["T22"][0] if data["Bench Analysis"]["B5"][0] != "n.a." else ""'],
		"B265": [None, 'data["PRINT"]["B241"][0]'],
		"C265": [None, 'data["Bench Analysis"]["J23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"F265": [None, 'data["Bench Analysis"]["K23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"I265": [None, 'data["Bench Analysis"]["R23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"L265": [None, 'data["Bench Analysis"]["S23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"O265": [None, 'data["Bench Analysis"]["T23"][0] if data["Bench Analysis"]["B6"][0] != "n.a." else ""'],
		"B266": [None, 'data["PRINT"]["B242"][0]'],
		"C266": [None, 'data["Bench Analysis"]["J24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"F266": [None, 'data["Bench Analysis"]["K24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"I266": [None, 'data["Bench Analysis"]["R24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"L266": [None, 'data["Bench Analysis"]["S24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"O266": [None, 'data["Bench Analysis"]["T24"][0] if data["Bench Analysis"]["B7"][0] != "n.a." else ""'],
		"B267": [None, 'data["PRINT"]["B243"][0]'],
		"C267": [None, 'data["Bench Analysis"]["J25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"F267": [None, 'data["Bench Analysis"]["K25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"I267": [None, 'data["Bench Analysis"]["R25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"L267": [None, 'data["Bench Analysis"]["S25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"O267": [None, 'data["Bench Analysis"]["T25"][0] if data["Bench Analysis"]["B8"][0] != "n.a." else ""'],
		"B268": [None, 'data["PRINT"]["B244"][0]'],
		"C268": [None, 'data["Bench Analysis"]["J26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"F268": [None, 'data["Bench Analysis"]["K26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"I268": [None, 'data["Bench Analysis"]["R26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"L268": [None, 'data["Bench Analysis"]["S26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"O268": [None, 'data["Bench Analysis"]["T26"][0] if data["Bench Analysis"]["B9"][0] != "n.a." else ""'],
		"B269": [None, 'data["PRINT"]["B245"][0]'],
		"C269": [None, 'data["Bench Analysis"]["J27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"F269": [None, 'data["Bench Analysis"]["K27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"I269": [None, 'data["Bench Analysis"]["R27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"L269": [None, 'data["Bench Analysis"]["S27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"O269": [None, 'data["Bench Analysis"]["T27"][0] if data["Bench Analysis"]["B10"][0] != "n.a." else ""'],
		"B270": [None, 'data["PRINT"]["B246"][0]'],
		"C270": [None, 'data["Bench Analysis"]["J28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"F270": [None, 'data["Bench Analysis"]["K28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"I270": [None, 'data["Bench Analysis"]["R28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"L270": [None, 'data["Bench Analysis"]["S28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"O270": [None, 'data["Bench Analysis"]["T28"][0] if data["Bench Analysis"]["B11"][0] != "n.a." else ""'],
		"B271": [None, 'data["PRINT"]["B247"][0]'],
		"C271": [None, 'data["Bench Analysis"]["J29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"F271": [None, 'data["Bench Analysis"]["K29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"I271": [None, 'data["Bench Analysis"]["R29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"L271": [None, 'data["Bench Analysis"]["S29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"O271": [None, 'data["Bench Analysis"]["T29"][0] if data["Bench Analysis"]["B12"][0] != "n.a." else ""'],
		"B272": [None, 'data["PRINT"]["B248"][0]'],
		"C272": [None, 'data["Bench Analysis"]["J30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"F272": [None, 'data["Bench Analysis"]["K30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"I272": [None, 'data["Bench Analysis"]["R30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"L272": [None, 'data["Bench Analysis"]["S30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"O272": [None, 'data["Bench Analysis"]["T30"][0] if data["Bench Analysis"]["B13"][0] != "n.a." else ""'],
		"B273": [None, 'data["PRINT"]["B249"][0]'],
		"C273": [None, 'data["Bench Analysis"]["J31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"F273": [None, 'data["Bench Analysis"]["K31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"I273": [None, 'data["Bench Analysis"]["R31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"L273": [None, 'data["Bench Analysis"]["S31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
		"O273": [None, 'data["Bench Analysis"]["T31"][0] if data["Bench Analysis"]["B14"][0] != "n.a." else ""'],
	},
}

# for the materials I don't use a dictionary of list because the values are constants, so is better to use a tuple
materials = \
{
	'ore': (22.7456, 0.4, 35, 0.4),
	'coal': (8.743, 0.35, None, 0.35),
	'pellet': (13.1194, 0.3, (30, 44), 0.35),
	'coke': (17.4959, 0.25, None, 0.25),
    'limestone': (17.4959, 0.5, (30, 44), 0.5)
}
